name: Build Masant Hotels APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-17-jdk \
            python3-pip python3-virtualenv \
            autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev \
            libncursesw5-dev libtinfo6 cmake \
            libffi-dev libssl-dev automake \
            autopoint gettext

      - name: Build APK
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: stable

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Masant-Hotels-APK
          path: ${{ steps.buildozer.outputs.filename }}
